version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ecowatch-network

  backend:
    image: ecowatch-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ecowatch
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - ecowatch-network

  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_DB=ecowatch
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecowatch-network

  redis:
    image: redis:7-alpine
    networks:
      - ecowatch-network

volumes:
  postgres_data:

networks:
  ecowatch-network:
    driver: bridge
